#!/usr/bin/env python3
"""Bake the equirectangular day texture for EarthClock and render a preview of
the sun-centred view exactly as the sketch draws it.

usage: bake_tex.py DAY.jpg OUT_DIR
"""
import sys, math, time, os
import numpy as np
from PIL import Image

day_path, out_dir = sys.argv[1:3]
W, H = 2048, 1024
R = 233
N = 2 * R

img = Image.open(day_path).convert("RGB").resize((W, H), Image.LANCZOS)
tex = np.asarray(img, dtype=np.float32) / 255.0
tex = np.clip((tex - 0.5) * 1.08 + 0.52, 0, 1)  # slight contrast lift


def rgb565(a):
    a8 = np.clip(a * 255 + 0.5, 0, 255).astype(np.uint16)
    return ((a8[..., 0] >> 3) << 11) | ((a8[..., 1] >> 2) << 5) | (a8[..., 2] >> 3)


t565 = rgb565(tex)
t565.astype("<u2").tofile(os.path.join(out_dir, "earth_tex.bin"))
with open(os.path.join(out_dir, "tex.h"), "w") as f:
    f.write("#pragma once\n// generated by tools/bake_tex.py - absolute path so .incbin resolves\n")
    f.write(f"#define TEX_W {W}\n#define TEX_H {H}\n")
    f.write(f'#define TEX_PATH "{os.path.join(os.path.abspath(out_dir), "earth_tex.bin")}"\n')


def sun_basis(unix):
    jd = unix / 86400.0 + 2440587.5
    n = jd - 2451545.0
    L = 280.460 + 0.9856474 * n
    g = math.radians(357.528 + 0.9856003 * n)
    lam = math.radians(L + 1.915 * math.sin(g) + 0.020 * math.sin(2 * g))
    eps = math.radians(23.439 - 4e-7 * n)
    dec = math.asin(math.sin(eps) * math.sin(lam))
    ra = math.atan2(math.cos(eps) * math.sin(lam), math.cos(lam))
    gmst = math.radians(280.46061837 + 360.98564736629 * n)
    sl = ra - gmst
    ex = np.array([-math.sin(sl), math.cos(sl), 0.0])
    ny = np.array([-math.sin(dec) * math.cos(sl), -math.sin(dec) * math.sin(sl), math.cos(dec)])
    zv = np.array([math.cos(dec) * math.cos(sl), math.cos(dec) * math.sin(sl), math.sin(dec)])
    return ex, ny, zv, math.degrees(dec), math.degrees(sl)


def shade_luts():
    z = (np.arange(256) + 0.5) / 256.0
    shade = 0.28 + 0.72 * z ** 0.55
    haze = 0.6 * (1 - z) ** 2.8
    return shade * (1 - haze), haze


def bilinear(u, v):
    x = u * W - 0.5
    y = np.clip(v * H - 0.5, 0, H - 1.001)
    x0 = np.floor(x).astype(int)
    y0 = np.floor(y).astype(int)
    fx = (x - x0)[..., None]
    fy = (y - y0)[..., None]
    x0 %= W
    x1 = (x0 + 1) % W
    y1 = np.minimum(y0 + 1, H - 1)
    return (tex[y0, x0] * (1 - fx) * (1 - fy) + tex[y0, x1] * fx * (1 - fy)
            + tex[y1, x0] * (1 - fx) * fy + tex[y1, x1] * fx * fy)


def render(unix, path):
    ex, ny, zv, dec, sl = sun_basis(unix)
    i = (np.arange(N) + 0.5 - R) / R
    X, Y = np.meshgrid(i, -i)
    rho = np.sqrt(X * X + Y * Y)
    Z = np.sqrt(np.clip(1 - rho * rho, 0, 1))
    P = X[..., None] * ex + Y[..., None] * ny + Z[..., None] * zv
    P /= np.maximum(np.linalg.norm(P, axis=-1, keepdims=True), 1e-9)
    lat = np.arcsin(np.clip(P[..., 2], -1, 1))
    lon = np.arctan2(P[..., 1], P[..., 0])
    c = bilinear((lon + math.pi) / (2 * math.pi), (math.pi / 2 - lat) / math.pi)
    sh, hz = shade_luts()
    zi = np.clip((Z * 255).astype(int), 0, 255)
    haze_col = np.array([0.42, 0.66, 1.0])
    out = c * sh[zi][..., None] + haze_col * hz[zi][..., None]
    alpha = np.clip((1 - rho) * R + 0.5, 0, 1)[..., None]
    canvas = np.zeros((466, 466, 3), np.float32)
    canvas[(466 - N) // 2:(466 - N) // 2 + N, (466 - N) // 2:(466 - N) // 2 + N] = np.clip(out, 0, 1) * alpha
    Image.fromarray((canvas * 255).astype(np.uint8)).save(path)
    print(f"subsolar lat {dec:.2f} lon {sl % 360 - (360 if sl % 360 > 180 else 0):.2f}")


render(time.time(), os.path.join(out_dir, "preview.png"))
print("baked", W, "x", H)
